TERMINAL_STATUSES = frozenset({"COMPLETED", "STOPPED_LIMIT", "NEED_HUMAN"})
PAUSABLE_FLOW_STAGES = frozenset(
    {
        "WAIT_INITIAL_CHOICE",
        "CAPTURING_INPUT",
        "CONFIRMING_TEXT",
        "WAIT_STUDENT_ACTION",
        "SHOWING_FULL_SOLUTION",
    }
)

STATUS_IN_PROGRESS = "IN_PROGRESS"
STATUS_COMPLETED = "COMPLETED"
STATUS_STOPPED_LIMIT = "STOPPED_LIMIT"
STATUS_NEED_HUMAN = "NEED_HUMAN"
STATUS_PAUSED = "PAUSED"
FLOW_STAGE_WAIT_INITIAL_CHOICE = "WAIT_INITIAL_CHOICE"
FLOW_STAGE_CAPTURING_INPUT = "CAPTURING_INPUT"
FLOW_STAGE_CONFIRMING_TEXT = "CONFIRMING_TEXT"
FLOW_STAGE_AI_EVALUATING = "AI_EVALUATING"
FLOW_STAGE_WAIT_STUDENT_ACTION = "WAIT_STUDENT_ACTION"
FLOW_STAGE_WAIT_GUIDED_ANSWERS = "WAIT_GUIDED_ANSWERS"
FLOW_STAGE_SHOWING_FULL_SOLUTION = "SHOWING_FULL_SOLUTION"


def can_pause(flow_stage: str) -> bool:
    return flow_stage in PAUSABLE_FLOW_STAGES


def flow_stage_after_initial_choice(choice: str) -> str:
    if choice == "KNOW":
        return FLOW_STAGE_CAPTURING_INPUT
    if choice in {"NOT_KNOW", "HAS_QUESTION"}:
        return FLOW_STAGE_WAIT_STUDENT_ACTION
    raise ValueError(f"不支持的初始选择：{choice}")
