TERMINAL_STATUSES = frozenset({"COMPLETED", "STOPPED_LIMIT", "NEED_HUMAN"})

STATUS_IN_PROGRESS = "IN_PROGRESS"
STATUS_COMPLETED = "COMPLETED"
STATUS_NEED_HUMAN = "NEED_HUMAN"
FLOW_STAGE_WAIT_INITIAL_CHOICE = "WAIT_INITIAL_CHOICE"
FLOW_STAGE_CAPTURING_INPUT = "CAPTURING_INPUT"
FLOW_STAGE_CONFIRMING_TEXT = "CONFIRMING_TEXT"
FLOW_STAGE_AI_EVALUATING = "AI_EVALUATING"
FLOW_STAGE_WAIT_STUDENT_ACTION = "WAIT_STUDENT_ACTION"


def flow_stage_after_initial_choice(choice: str) -> str:
    if choice == "KNOW":
        return FLOW_STAGE_CAPTURING_INPUT
    if choice == "NOT_KNOW":
        return FLOW_STAGE_WAIT_STUDENT_ACTION
    raise ValueError(f"不支持的初始选择：{choice}")
